### ISSUE TITLE
How to add react-dom definition?

### ISSUE THREAD

**Issue by chandrush** [retyped/react-tsd-ambient#1]
Hello!
I tried your beautifull utility for this package. It generated one symlink only for react module. But I also want a symlink for react-dom. What I have to do?

Thank you!

**Comment by shyiko** [comment]
Hi. All the packages under https://github.com/retyped (including this one) were converted from DefinitelyTyped is automated manner. Unfortunately while (in some cases) there are multiple declarations per module only one was included. I've corrected package.json and re-published. [tsdm](https://github.com/shyiko/tsdm) is going to get a mechanism to resolve cases like this at the beginning of the next week. Thank you for the heads up!
